/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class NativeInvoke */

#ifndef _Included_NativeInvoke
#define _Included_NativeInvoke
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     NativeInvoke
 * Method:    getTime
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_NativeInvoke_getTime
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
