// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf_proto.proto

import com.google.protobuf.AbstractMessage;

public final class PbDemoProto {
    private static com.google.protobuf.Descriptors.Descriptor
        internal_static_com_taobao_teaey_protobuf_MsgFields_descriptor;
    private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internal_static_com_taobao_teaey_protobuf_MsgFields_fieldAccessorTable;
    private static com.google.protobuf.Descriptors.Descriptor
        internal_static_com_taobao_teaey_protobuf_Login_C2S_descriptor;
    private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internal_static_com_taobao_teaey_protobuf_Login_C2S_fieldAccessorTable;
    private static com.google.protobuf.Descriptors.Descriptor
        internal_static_com_taobao_teaey_protobuf_Login_S2C_descriptor;
    private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internal_static_com_taobao_teaey_protobuf_Login_S2C_fieldAccessorTable;
    private static com.google.protobuf.Descriptors.FileDescriptor
        descriptor;
    static {
        java.lang.String[] descriptorData = {
            "\n\024protobuf_proto.proto\022\031com.taobao.teaey" +
                ".protobuf\"\013\n\tMsgFields\"\036\n\tLogin_C2S\022\021\n\tt" +
                "imestamp\030\001 \002(\003\"\036\n\tLogin_S2C\022\021\n\ttimestamp" +
                "\030\001 \002(\0032c\n\014LoginService\022S\n\005login\022$.com.ta" +
                "obao.teaey.protobuf.Login_C2S\032$.com.taob" +
                "ao.teaey.protobuf.Login_S2CB\022B\013PbDemoPro" +
                "toH\001\210\001\001"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
            new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
                public com.google.protobuf.ExtensionRegistry assignDescriptors(
                    com.google.protobuf.Descriptors.FileDescriptor root) {
                    descriptor = root;
                    internal_static_com_taobao_teaey_protobuf_MsgFields_descriptor =
                        getDescriptor().getMessageTypes().get(0);
                    internal_static_com_taobao_teaey_protobuf_MsgFields_fieldAccessorTable = new
                        com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                        internal_static_com_taobao_teaey_protobuf_MsgFields_descriptor,
                        new java.lang.String[] {});
                    internal_static_com_taobao_teaey_protobuf_Login_C2S_descriptor =
                        getDescriptor().getMessageTypes().get(1);
                    internal_static_com_taobao_teaey_protobuf_Login_C2S_fieldAccessorTable = new
                        com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                        internal_static_com_taobao_teaey_protobuf_Login_C2S_descriptor,
                        new java.lang.String[] {"Timestamp",});
                    internal_static_com_taobao_teaey_protobuf_Login_S2C_descriptor =
                        getDescriptor().getMessageTypes().get(2);
                    internal_static_com_taobao_teaey_protobuf_Login_S2C_fieldAccessorTable = new
                        com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                        internal_static_com_taobao_teaey_protobuf_Login_S2C_descriptor,
                        new java.lang.String[] {"Timestamp",});
                    return null;
                }
            };
        com.google.protobuf.Descriptors.FileDescriptor
            .internalBuildGeneratedFileFrom(descriptorData,
                new com.google.protobuf.Descriptors.FileDescriptor[] {
                }, assigner
            );
    }


    private PbDemoProto() {
    }

    public static void registerAllExtensions(
        com.google.protobuf.ExtensionRegistry registry) {
    }

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }
    public interface MsgFieldsOrBuilder
        extends com.google.protobuf.MessageOrBuilder {
    }
    public interface Login_C2SOrBuilder
        extends com.google.protobuf.MessageOrBuilder {

        // required int64 timestamp = 1;

        /**
         * <code>required int64 timestamp = 1;</code>
         */
        boolean hasTimestamp();

        /**
         * <code>required int64 timestamp = 1;</code>
         */
        long getTimestamp();
    }
    public interface Login_S2COrBuilder
        extends com.google.protobuf.MessageOrBuilder {

        // required int64 timestamp = 1;

        /**
         * <code>required int64 timestamp = 1;</code>
         */
        boolean hasTimestamp();

        /**
         * <code>required int64 timestamp = 1;</code>
         */
        long getTimestamp();
    }


    /**
     * Protobuf type {@code com.taobao.teaey.protobuf.MsgFields}
     */
    public static final class MsgFields extends
        com.google.protobuf.GeneratedMessage
        implements MsgFieldsOrBuilder {
        private static final MsgFields defaultInstance;
        private static final long serialVersionUID = 0L;
        public static com.google.protobuf.Parser<MsgFields> PARSER =
            new com.google.protobuf.AbstractParser<MsgFields>() {
                public MsgFields parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                    return new MsgFields(input, extensionRegistry);
                }
            };
        private final com.google.protobuf.UnknownFieldSet unknownFields;
        private byte memoizedIsInitialized = -1;
        private int memoizedSerializedSize = -1;

        // Use MsgFields.newBuilder() to construct.
        private MsgFields(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
            super(builder);
            this.unknownFields = builder.getUnknownFields();
        }

        private MsgFields(boolean noInit) {
            this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance();
        }

        private MsgFields(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
            initFields();
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!parseUnknownField(input, unknownFields,
                                extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static MsgFields getDefaultInstance() {
            return defaultInstance;
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return PbDemoProto.internal_static_com_taobao_teaey_protobuf_MsgFields_descriptor;
        }

        public static PbDemoProto.MsgFields parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static PbDemoProto.MsgFields parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static PbDemoProto.MsgFields parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static PbDemoProto.MsgFields parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static PbDemoProto.MsgFields parseFrom(
            java.io.InputStream input)
            throws java.io.IOException {
            return PARSER.parseFrom(input);
        }

        public static PbDemoProto.MsgFields parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
            return PARSER.parseFrom(input, extensionRegistry);
        }

        public static PbDemoProto.MsgFields parseDelimitedFrom(
            java.io.InputStream input)
            throws java.io.IOException {
            return PARSER.parseDelimitedFrom(input);
        }

        public static PbDemoProto.MsgFields parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
            return PARSER.parseDelimitedFrom(input, extensionRegistry);
        }

        public static PbDemoProto.MsgFields parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
            return PARSER.parseFrom(input);
        }

        public static PbDemoProto.MsgFields parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
            return PARSER.parseFrom(input, extensionRegistry);
        }

        public static Builder newBuilder() {
            return Builder.create();
        }

        public static Builder newBuilder(
            PbDemoProto.MsgFields prototype) {
            return newBuilder().mergeFrom(prototype);
        }

        public MsgFields getDefaultInstanceForType() {
            return defaultInstance;
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return PbDemoProto.internal_static_com_taobao_teaey_protobuf_MsgFields_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                    PbDemoProto.MsgFields.class,
                    PbDemoProto.MsgFields.Builder.class);
        }

        @java.lang.Override
        public com.google.protobuf.Parser<MsgFields> getParserForType() {
            return PARSER;
        }

        private void initFields() {
        }

        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized != -1) {
                return isInitialized == 1;
            }

            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException {
            getSerializedSize();
            getUnknownFields().writeTo(output);
        }

        public int getSerializedSize() {
            int size = memoizedSerializedSize;
            if (size != -1) {
                return size;
            }

            size = 0;
            size += getUnknownFields().getSerializedSize();
            memoizedSerializedSize = size;
            return size;
        }

        @java.lang.Override
        protected java.lang.Object writeReplace()
            throws java.io.ObjectStreamException {
            return super.writeReplace();
        }

        public Builder newBuilderForType() {
            return newBuilder();
        }

        public Builder toBuilder() {
            return newBuilder(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code com.taobao.teaey.protobuf.MsgFields}
         */
        public static final class Builder extends
            com.google.protobuf.GeneratedMessage.Builder<Builder>
            implements PbDemoProto.MsgFieldsOrBuilder {
            // Construct using PbDemoProto.MsgFields.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                com.google.protobuf.GeneratedMessage.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return PbDemoProto.internal_static_com_taobao_teaey_protobuf_MsgFields_descriptor;
            }

            private static Builder create() {
                return new Builder();
            }

            protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return PbDemoProto.internal_static_com_taobao_teaey_protobuf_MsgFields_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                        PbDemoProto.MsgFields.class,
                        PbDemoProto.MsgFields.Builder.class);
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
                }
            }

            public Builder clear() {
                super.clear();
                return this;
            }

            public Builder clone() {
                return create().mergeFrom(buildPartial());
            }

            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return PbDemoProto.internal_static_com_taobao_teaey_protobuf_MsgFields_descriptor;
            }

            public PbDemoProto.MsgFields getDefaultInstanceForType() {
                return PbDemoProto.MsgFields.getDefaultInstance();
            }

            public PbDemoProto.MsgFields build() {
                PbDemoProto.MsgFields result = buildPartial();
                if (!result.isInitialized()) {
                    throw AbstractMessage.Builder.newUninitializedMessageException(result);
                }
                return result;
            }

            public PbDemoProto.MsgFields buildPartial() {
                PbDemoProto.MsgFields result =
                    new PbDemoProto.MsgFields(this);
                onBuilt();
                return result;
            }

            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof PbDemoProto.MsgFields) {
                    return mergeFrom((PbDemoProto.MsgFields) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(PbDemoProto.MsgFields other) {
                if (other == PbDemoProto.MsgFields.getDefaultInstance()) {
                    return this;
                }
                this.mergeUnknownFields(other.getUnknownFields());
                return this;
            }

            public final boolean isInitialized() {
                return true;
            }

            public Builder mergeFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
                PbDemoProto.MsgFields parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage =
                        (PbDemoProto.MsgFields) e.getUnfinishedMessage();
                    throw e;
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            // @@protoc_insertion_point(builder_scope:com.taobao.teaey.protobuf.MsgFields)
        }


        static {
            defaultInstance = new MsgFields(true);
            defaultInstance.initFields();
        }

        // @@protoc_insertion_point(class_scope:com.taobao.teaey.protobuf.MsgFields)
    }


    /**
     * Protobuf type {@code com.taobao.teaey.protobuf.Login_C2S}
     */
    public static final class Login_C2S extends
        com.google.protobuf.GeneratedMessage
        implements Login_C2SOrBuilder {
        // required int64 timestamp = 1;
        public static final int TIMESTAMP_FIELD_NUMBER = 1;
        private static final Login_C2S defaultInstance;
        private static final long serialVersionUID = 0L;
        public static com.google.protobuf.Parser<Login_C2S> PARSER =
            new com.google.protobuf.AbstractParser<Login_C2S>() {
                public Login_C2S parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                    return new Login_C2S(input, extensionRegistry);
                }
            };
        private final com.google.protobuf.UnknownFieldSet unknownFields;
        private int bitField0_;
        private long timestamp_;
        private byte memoizedIsInitialized = -1;
        private int memoizedSerializedSize = -1;

        // Use Login_C2S.newBuilder() to construct.
        private Login_C2S(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
            super(builder);
            this.unknownFields = builder.getUnknownFields();
        }

        private Login_C2S(boolean noInit) {
            this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance();
        }

        private Login_C2S(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
            initFields();
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!parseUnknownField(input, unknownFields,
                                extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 8: {
                            bitField0_ |= 0x00000001;
                            timestamp_ = input.readInt64();
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static Login_C2S getDefaultInstance() {
            return defaultInstance;
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return PbDemoProto.internal_static_com_taobao_teaey_protobuf_Login_C2S_descriptor;
        }

        public static PbDemoProto.Login_C2S parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static PbDemoProto.Login_C2S parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static PbDemoProto.Login_C2S parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static PbDemoProto.Login_C2S parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static PbDemoProto.Login_C2S parseFrom(
            java.io.InputStream input)
            throws java.io.IOException {
            return PARSER.parseFrom(input);
        }

        public static PbDemoProto.Login_C2S parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
            return PARSER.parseFrom(input, extensionRegistry);
        }

        public static PbDemoProto.Login_C2S parseDelimitedFrom(
            java.io.InputStream input)
            throws java.io.IOException {
            return PARSER.parseDelimitedFrom(input);
        }

        public static PbDemoProto.Login_C2S parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
            return PARSER.parseDelimitedFrom(input, extensionRegistry);
        }

        public static PbDemoProto.Login_C2S parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
            return PARSER.parseFrom(input);
        }

        public static PbDemoProto.Login_C2S parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
            return PARSER.parseFrom(input, extensionRegistry);
        }

        public static Builder newBuilder() {
            return Builder.create();
        }

        public static Builder newBuilder(
            PbDemoProto.Login_C2S prototype) {
            return newBuilder().mergeFrom(prototype);
        }

        public Login_C2S getDefaultInstanceForType() {
            return defaultInstance;
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return PbDemoProto.internal_static_com_taobao_teaey_protobuf_Login_C2S_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                    PbDemoProto.Login_C2S.class,
                    PbDemoProto.Login_C2S.Builder.class);
        }

        @java.lang.Override
        public com.google.protobuf.Parser<Login_C2S> getParserForType() {
            return PARSER;
        }

        /**
         * <code>required int64 timestamp = 1;</code>
         */
        public boolean hasTimestamp() {
            return ((bitField0_ & 0x00000001) == 0x00000001);
        }

        /**
         * <code>required int64 timestamp = 1;</code>
         */
        public long getTimestamp() {
            return timestamp_;
        }

        private void initFields() {
            timestamp_ = 0L;
        }

        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized != -1) {
                return isInitialized == 1;
            }

            if (!hasTimestamp()) {
                memoizedIsInitialized = 0;
                return false;
            }
            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException {
            getSerializedSize();
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                output.writeInt64(1, timestamp_);
            }
            getUnknownFields().writeTo(output);
        }

        public int getSerializedSize() {
            int size = memoizedSerializedSize;
            if (size != -1) {
                return size;
            }

            size = 0;
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                size += com.google.protobuf.CodedOutputStream
                    .computeInt64Size(1, timestamp_);
            }
            size += getUnknownFields().getSerializedSize();
            memoizedSerializedSize = size;
            return size;
        }

        @java.lang.Override
        protected java.lang.Object writeReplace()
            throws java.io.ObjectStreamException {
            return super.writeReplace();
        }

        public Builder newBuilderForType() {
            return newBuilder();
        }

        public Builder toBuilder() {
            return newBuilder(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code com.taobao.teaey.protobuf.Login_C2S}
         */
        public static final class Builder extends
            com.google.protobuf.GeneratedMessage.Builder<Builder>
            implements PbDemoProto.Login_C2SOrBuilder {
            private int bitField0_;
            // required int64 timestamp = 1;
            private long timestamp_;

            // Construct using PbDemoProto.Login_C2S.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                com.google.protobuf.GeneratedMessage.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return PbDemoProto.internal_static_com_taobao_teaey_protobuf_Login_C2S_descriptor;
            }

            private static Builder create() {
                return new Builder();
            }

            protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return PbDemoProto.internal_static_com_taobao_teaey_protobuf_Login_C2S_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                        PbDemoProto.Login_C2S.class,
                        PbDemoProto.Login_C2S.Builder.class);
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
                }
            }

            public Builder clear() {
                super.clear();
                timestamp_ = 0L;
                bitField0_ = (bitField0_ & ~0x00000001);
                return this;
            }

            public Builder clone() {
                return create().mergeFrom(buildPartial());
            }

            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return PbDemoProto.internal_static_com_taobao_teaey_protobuf_Login_C2S_descriptor;
            }

            public PbDemoProto.Login_C2S getDefaultInstanceForType() {
                return PbDemoProto.Login_C2S.getDefaultInstance();
            }

            public PbDemoProto.Login_C2S build() {
                PbDemoProto.Login_C2S result = buildPartial();
                if (!result.isInitialized()) {
                    throw AbstractMessage.Builder.newUninitializedMessageException(result);
                }
                return result;
            }

            public PbDemoProto.Login_C2S buildPartial() {
                PbDemoProto.Login_C2S result =
                    new PbDemoProto.Login_C2S(this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
                    to_bitField0_ |= 0x00000001;
                }
                result.timestamp_ = timestamp_;
                result.bitField0_ = to_bitField0_;
                onBuilt();
                return result;
            }

            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof PbDemoProto.Login_C2S) {
                    return mergeFrom((PbDemoProto.Login_C2S) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(PbDemoProto.Login_C2S other) {
                if (other == PbDemoProto.Login_C2S.getDefaultInstance()) {
                    return this;
                }
                if (other.hasTimestamp()) {
                    setTimestamp(other.getTimestamp());
                }
                this.mergeUnknownFields(other.getUnknownFields());
                return this;
            }

            public final boolean isInitialized() {
                if (!hasTimestamp()) {

                    return false;
                }
                return true;
            }

            public Builder mergeFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
                PbDemoProto.Login_C2S parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage =
                        (PbDemoProto.Login_C2S) e.getUnfinishedMessage();
                    throw e;
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            /**
             * <code>required int64 timestamp = 1;</code>
             */
            public boolean hasTimestamp() {
                return ((bitField0_ & 0x00000001) == 0x00000001);
            }

            /**
             * <code>required int64 timestamp = 1;</code>
             */
            public long getTimestamp() {
                return timestamp_;
            }

            /**
             * <code>required int64 timestamp = 1;</code>
             */
            public Builder setTimestamp(long value) {
                bitField0_ |= 0x00000001;
                timestamp_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>required int64 timestamp = 1;</code>
             */
            public Builder clearTimestamp() {
                bitField0_ = (bitField0_ & ~0x00000001);
                timestamp_ = 0L;
                onChanged();
                return this;
            }

            // @@protoc_insertion_point(builder_scope:com.taobao.teaey.protobuf.Login_C2S)
        }


        static {
            defaultInstance = new Login_C2S(true);
            defaultInstance.initFields();
        }

        // @@protoc_insertion_point(class_scope:com.taobao.teaey.protobuf.Login_C2S)
    }


    /**
     * Protobuf type {@code com.taobao.teaey.protobuf.Login_S2C}
     */
    public static final class Login_S2C extends
        com.google.protobuf.GeneratedMessage
        implements Login_S2COrBuilder {
        // required int64 timestamp = 1;
        public static final int TIMESTAMP_FIELD_NUMBER = 1;
        private static final Login_S2C defaultInstance;
        private static final long serialVersionUID = 0L;
        public static com.google.protobuf.Parser<Login_S2C> PARSER =
            new com.google.protobuf.AbstractParser<Login_S2C>() {
                public Login_S2C parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                    return new Login_S2C(input, extensionRegistry);
                }
            };
        private final com.google.protobuf.UnknownFieldSet unknownFields;
        private int bitField0_;
        private long timestamp_;
        private byte memoizedIsInitialized = -1;
        private int memoizedSerializedSize = -1;

        // Use Login_S2C.newBuilder() to construct.
        private Login_S2C(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
            super(builder);
            this.unknownFields = builder.getUnknownFields();
        }

        private Login_S2C(boolean noInit) {
            this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance();
        }

        private Login_S2C(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
            initFields();
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!parseUnknownField(input, unknownFields,
                                extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 8: {
                            bitField0_ |= 0x00000001;
                            timestamp_ = input.readInt64();
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static Login_S2C getDefaultInstance() {
            return defaultInstance;
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return PbDemoProto.internal_static_com_taobao_teaey_protobuf_Login_S2C_descriptor;
        }

        public static PbDemoProto.Login_S2C parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static PbDemoProto.Login_S2C parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static PbDemoProto.Login_S2C parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static PbDemoProto.Login_S2C parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static PbDemoProto.Login_S2C parseFrom(
            java.io.InputStream input)
            throws java.io.IOException {
            return PARSER.parseFrom(input);
        }

        public static PbDemoProto.Login_S2C parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
            return PARSER.parseFrom(input, extensionRegistry);
        }

        public static PbDemoProto.Login_S2C parseDelimitedFrom(
            java.io.InputStream input)
            throws java.io.IOException {
            return PARSER.parseDelimitedFrom(input);
        }

        public static PbDemoProto.Login_S2C parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
            return PARSER.parseDelimitedFrom(input, extensionRegistry);
        }

        public static PbDemoProto.Login_S2C parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
            return PARSER.parseFrom(input);
        }

        public static PbDemoProto.Login_S2C parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
            return PARSER.parseFrom(input, extensionRegistry);
        }

        public static Builder newBuilder() {
            return Builder.create();
        }

        public static Builder newBuilder(
            PbDemoProto.Login_S2C prototype) {
            return newBuilder().mergeFrom(prototype);
        }

        public Login_S2C getDefaultInstanceForType() {
            return defaultInstance;
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return PbDemoProto.internal_static_com_taobao_teaey_protobuf_Login_S2C_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                    PbDemoProto.Login_S2C.class,
                    PbDemoProto.Login_S2C.Builder.class);
        }

        @java.lang.Override
        public com.google.protobuf.Parser<Login_S2C> getParserForType() {
            return PARSER;
        }

        /**
         * <code>required int64 timestamp = 1;</code>
         */
        public boolean hasTimestamp() {
            return ((bitField0_ & 0x00000001) == 0x00000001);
        }

        /**
         * <code>required int64 timestamp = 1;</code>
         */
        public long getTimestamp() {
            return timestamp_;
        }

        private void initFields() {
            timestamp_ = 0L;
        }

        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized != -1) {
                return isInitialized == 1;
            }

            if (!hasTimestamp()) {
                memoizedIsInitialized = 0;
                return false;
            }
            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException {
            getSerializedSize();
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                output.writeInt64(1, timestamp_);
            }
            getUnknownFields().writeTo(output);
        }

        public int getSerializedSize() {
            int size = memoizedSerializedSize;
            if (size != -1) {
                return size;
            }

            size = 0;
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                size += com.google.protobuf.CodedOutputStream
                    .computeInt64Size(1, timestamp_);
            }
            size += getUnknownFields().getSerializedSize();
            memoizedSerializedSize = size;
            return size;
        }

        @java.lang.Override
        protected java.lang.Object writeReplace()
            throws java.io.ObjectStreamException {
            return super.writeReplace();
        }

        public Builder newBuilderForType() {
            return newBuilder();
        }

        public Builder toBuilder() {
            return newBuilder(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code com.taobao.teaey.protobuf.Login_S2C}
         */
        public static final class Builder extends
            com.google.protobuf.GeneratedMessage.Builder<Builder>
            implements PbDemoProto.Login_S2COrBuilder {
            private int bitField0_;
            // required int64 timestamp = 1;
            private long timestamp_;

            // Construct using PbDemoProto.Login_S2C.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                com.google.protobuf.GeneratedMessage.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return PbDemoProto.internal_static_com_taobao_teaey_protobuf_Login_S2C_descriptor;
            }

            private static Builder create() {
                return new Builder();
            }

            protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return PbDemoProto.internal_static_com_taobao_teaey_protobuf_Login_S2C_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                        PbDemoProto.Login_S2C.class,
                        PbDemoProto.Login_S2C.Builder.class);
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
                }
            }

            public Builder clear() {
                super.clear();
                timestamp_ = 0L;
                bitField0_ = (bitField0_ & ~0x00000001);
                return this;
            }

            public Builder clone() {
                return create().mergeFrom(buildPartial());
            }

            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return PbDemoProto.internal_static_com_taobao_teaey_protobuf_Login_S2C_descriptor;
            }

            public PbDemoProto.Login_S2C getDefaultInstanceForType() {
                return PbDemoProto.Login_S2C.getDefaultInstance();
            }

            public PbDemoProto.Login_S2C build() {
                PbDemoProto.Login_S2C result = buildPartial();
                if (!result.isInitialized()) {
                    throw AbstractMessage.Builder.newUninitializedMessageException(result);
                }
                return result;
            }

            public PbDemoProto.Login_S2C buildPartial() {
                PbDemoProto.Login_S2C result =
                    new PbDemoProto.Login_S2C(this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
                    to_bitField0_ |= 0x00000001;
                }
                result.timestamp_ = timestamp_;
                result.bitField0_ = to_bitField0_;
                onBuilt();
                return result;
            }

            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof PbDemoProto.Login_S2C) {
                    return mergeFrom((PbDemoProto.Login_S2C) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(PbDemoProto.Login_S2C other) {
                if (other == PbDemoProto.Login_S2C.getDefaultInstance()) {
                    return this;
                }
                if (other.hasTimestamp()) {
                    setTimestamp(other.getTimestamp());
                }
                this.mergeUnknownFields(other.getUnknownFields());
                return this;
            }

            public final boolean isInitialized() {
                if (!hasTimestamp()) {

                    return false;
                }
                return true;
            }

            public Builder mergeFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
                PbDemoProto.Login_S2C parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage =
                        (PbDemoProto.Login_S2C) e.getUnfinishedMessage();
                    throw e;
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            /**
             * <code>required int64 timestamp = 1;</code>
             */
            public boolean hasTimestamp() {
                return ((bitField0_ & 0x00000001) == 0x00000001);
            }

            /**
             * <code>required int64 timestamp = 1;</code>
             */
            public long getTimestamp() {
                return timestamp_;
            }

            /**
             * <code>required int64 timestamp = 1;</code>
             */
            public Builder setTimestamp(long value) {
                bitField0_ |= 0x00000001;
                timestamp_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>required int64 timestamp = 1;</code>
             */
            public Builder clearTimestamp() {
                bitField0_ = (bitField0_ & ~0x00000001);
                timestamp_ = 0L;
                onChanged();
                return this;
            }

            // @@protoc_insertion_point(builder_scope:com.taobao.teaey.protobuf.Login_S2C)
        }


        static {
            defaultInstance = new Login_S2C(true);
            defaultInstance.initFields();
        }

        // @@protoc_insertion_point(class_scope:com.taobao.teaey.protobuf.Login_S2C)
    }


    /**
     * Protobuf service {@code com.taobao.teaey.protobuf.LoginService}
     */
    public static abstract class LoginService
        implements com.google.protobuf.Service {
        protected LoginService() {
        }

        public static com.google.protobuf.Service newReflectiveService(
            final Interface impl) {
            return new LoginService() {
                @java.lang.Override
                public void login(
                    com.google.protobuf.RpcController controller,
                    PbDemoProto.Login_C2S request,
                    com.google.protobuf.RpcCallback<PbDemoProto.Login_S2C> done) {
                    impl.login(controller, request, done);
                }

            };
        }

        public static com.google.protobuf.BlockingService
        newReflectiveBlockingService(final BlockingInterface impl) {
            return new com.google.protobuf.BlockingService() {
                public final com.google.protobuf.Descriptors.ServiceDescriptor
                getDescriptorForType() {
                    return getDescriptor();
                }

                public final com.google.protobuf.Message callBlockingMethod(
                    com.google.protobuf.Descriptors.MethodDescriptor method,
                    com.google.protobuf.RpcController controller,
                    com.google.protobuf.Message request)
                    throws com.google.protobuf.ServiceException {
                    if (method.getService() != getDescriptor()) {
                        throw new java.lang.IllegalArgumentException(
                            "Service.callBlockingMethod() given method descriptor for " +
                                "wrong service type."
                        );
                    }
                    switch (method.getIndex()) {
                        case 0:
                            return impl.login(controller,
                                (PbDemoProto.Login_C2S) request);
                        default:
                            throw new java.lang.AssertionError("Can't get here.");
                    }
                }

                public final com.google.protobuf.Message
                getRequestPrototype(
                    com.google.protobuf.Descriptors.MethodDescriptor method) {
                    if (method.getService() != getDescriptor()) {
                        throw new java.lang.IllegalArgumentException(
                            "Service.getRequestPrototype() given method " +
                                "descriptor for wrong service type."
                        );
                    }
                    switch (method.getIndex()) {
                        case 0:
                            return PbDemoProto.Login_C2S
                                .getDefaultInstance();
                        default:
                            throw new java.lang.AssertionError("Can't get here.");
                    }
                }

                public final com.google.protobuf.Message
                getResponsePrototype(
                    com.google.protobuf.Descriptors.MethodDescriptor method) {
                    if (method.getService() != getDescriptor()) {
                        throw new java.lang.IllegalArgumentException(
                            "Service.getResponsePrototype() given method " +
                                "descriptor for wrong service type."
                        );
                    }
                    switch (method.getIndex()) {
                        case 0:
                            return PbDemoProto.Login_S2C
                                .getDefaultInstance();
                        default:
                            throw new java.lang.AssertionError("Can't get here.");
                    }
                }

            };
        }

        public static final com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptor() {
            return PbDemoProto.getDescriptor().getServices().get(0);
        }

        public static Stub newStub(
            com.google.protobuf.RpcChannel channel) {
            return new Stub(channel);
        }

        public static BlockingInterface newBlockingStub(
            com.google.protobuf.BlockingRpcChannel channel) {
            return new BlockingStub(channel);
        }

        /**
         * <code>rpc login(.com.taobao.teaey.protobuf.Login_C2S) returns (.com.taobao.teaey.protobuf.Login_S2C);</code>
         */
        public abstract void login(
            com.google.protobuf.RpcController controller,
            PbDemoProto.Login_C2S request,
            com.google.protobuf.RpcCallback<PbDemoProto.Login_S2C> done);

        public final com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptorForType() {
            return getDescriptor();
        }

        public final void callMethod(
            com.google.protobuf.Descriptors.MethodDescriptor method,
            com.google.protobuf.RpcController controller,
            com.google.protobuf.Message request,
            com.google.protobuf.RpcCallback<
                com.google.protobuf.Message> done) {
            if (method.getService() != getDescriptor()) {
                throw new java.lang.IllegalArgumentException(
                    "Service.callMethod() given method descriptor for wrong " +
                        "service type."
                );
            }
            switch (method.getIndex()) {
                case 0:
                    this.login(controller,
                        (PbDemoProto.Login_C2S) request,
                        com.google.protobuf.RpcUtil
                            .<PbDemoProto.Login_S2C>specializeCallback(
                                done)
                    );
                    return;
                default:
                    throw new java.lang.AssertionError("Can't get here.");
            }
        }

        public final com.google.protobuf.Message
        getRequestPrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
            if (method.getService() != getDescriptor()) {
                throw new java.lang.IllegalArgumentException(
                    "Service.getRequestPrototype() given method " +
                        "descriptor for wrong service type."
                );
            }
            switch (method.getIndex()) {
                case 0:
                    return PbDemoProto.Login_C2S.getDefaultInstance();
                default:
                    throw new java.lang.AssertionError("Can't get here.");
            }
        }

        public final com.google.protobuf.Message
        getResponsePrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
            if (method.getService() != getDescriptor()) {
                throw new java.lang.IllegalArgumentException(
                    "Service.getResponsePrototype() given method " +
                        "descriptor for wrong service type."
                );
            }
            switch (method.getIndex()) {
                case 0:
                    return PbDemoProto.Login_S2C.getDefaultInstance();
                default:
                    throw new java.lang.AssertionError("Can't get here.");
            }
        }

        public interface Interface {
            /**
             * <code>rpc login(.com.taobao.teaey.protobuf.Login_C2S) returns (.com.taobao.teaey.protobuf.Login_S2C);</code>
             */
            public abstract void login(
                com.google.protobuf.RpcController controller,
                PbDemoProto.Login_C2S request,
                com.google.protobuf.RpcCallback<PbDemoProto.Login_S2C> done);

        }

        public interface BlockingInterface {
            public PbDemoProto.Login_S2C login(
                com.google.protobuf.RpcController controller,
                PbDemoProto.Login_C2S request)
                throws com.google.protobuf.ServiceException;
        }


        public static final class Stub extends PbDemoProto.LoginService
            implements Interface {
            private final com.google.protobuf.RpcChannel channel;

            private Stub(com.google.protobuf.RpcChannel channel) {
                this.channel = channel;
            }

            public com.google.protobuf.RpcChannel getChannel() {
                return channel;
            }

            public void login(
                com.google.protobuf.RpcController controller,
                PbDemoProto.Login_C2S request,
                com.google.protobuf.RpcCallback<PbDemoProto.Login_S2C> done) {
                channel.callMethod(
                    getDescriptor().getMethods().get(0),
                    controller,
                    request,
                    PbDemoProto.Login_S2C.getDefaultInstance(),
                    com.google.protobuf.RpcUtil.generalizeCallback(
                        done,
                        PbDemoProto.Login_S2C.class,
                        PbDemoProto.Login_S2C.getDefaultInstance())
                );
            }
        }


        private static final class BlockingStub implements BlockingInterface {
            private final com.google.protobuf.BlockingRpcChannel channel;

            private BlockingStub(com.google.protobuf.BlockingRpcChannel channel) {
                this.channel = channel;
            }

            public PbDemoProto.Login_S2C login(
                com.google.protobuf.RpcController controller,
                PbDemoProto.Login_C2S request)
                throws com.google.protobuf.ServiceException {
                return (PbDemoProto.Login_S2C) channel.callBlockingMethod(
                    getDescriptor().getMethods().get(0),
                    controller,
                    request,
                    PbDemoProto.Login_S2C.getDefaultInstance());
            }

        }

        // @@protoc_insertion_point(class_scope:com.taobao.teaey.protobuf.LoginService)
    }

    // @@protoc_insertion_point(outer_class_scope)
}
